### ISSUE TITLE
About Makefile

### ISSUE THREAD

**Issue by YixinZhang92** [RadPattern/RadPattern2017#28]
Please make sure to update your own Makefile to the new version, so that we can get rid of all warnings (except the one for "Goodbye", that is caused by the ";" after "I have completed running all the prototypes,\n").

**Comment by oluwaseunfadugba** [comment]
Nice nice. I think you should make corresponding .h files for the new .cpp files as well. Good job!
Cheers sis! 

    On Monday, April 10, 2017 2:10 PM, YixinZhang92 <notifications@github.com> wrote:
 

 Please make sure to update your own Makefile to the new version, so that we can get rid of all warnings (except the one for "Goodbye", that is caused by the ";" after "I have completed running all the prototypes,\n").—
