### ISSUE TITLE
A lot of changes made

### ISSUE THREAD

**Issue by jamboee** [RadPattern/RadPattern2017#33]
I finished working on functions for radiation pattern, gaussian function and its derivatives and conversion(cartesian to spherical). I added .h files for the .cpp files that needed them. some of the things i did may not be necessary. I didn't want to make a pull request before u check and double check everything I did if it's working the way it should because i touched on many files than just mine. Let me know how it's working then I will commit to the organization. Thank you. Please take ur time to review my work. I don't wanna mess things up. Take a look at my repository @oluwaseunfadugba @YixinZhang92

**Comment by oluwaseunfadugba** [comment]
Hey bro,
Thank you so much for the great job. I will check it after my meeting this morning. 
Cheers,Oluwaseun 

    On Tuesday, April 11, 2017 10:29 PM, jamboee <notifications@github.com> wrote:
 

 I finished working on functions for radiation pattern, gaussian function and its derivatives and conversion(cartesian to spherical). I added .h files for the .cpp files that needed them. some of the things i did may not be necessary. I didn't want to make a pull request before u check and double check everything I did if it's working the way it should because i touched on many files than just mine. Let me know how it's working then I will commit to the organization. Thank you. Please take ur time to review my work. I don't wanna mess things up.—

**Comment by YixinZhang92** [comment]
Hi Eric, 

I have checked, they worked very well for me. Thanks a lot for your work. Just be careful when merge them.

**Comment by jamboee** [comment]
do you guys mind making a copy of your local repository on the side just in case the merge causes problems. 
@oluwaseunfadugba when you are calculating displacement, are the angles supposed to be in radians or degrees? I'm asking because in the equations it looks like you are doing a conversion. FYI when I was doing the Cartesian to spherical conversion, the resulted angles are in degrees.

**Comment by YixinZhang92** [comment]
Sure, I have done that.

**Comment by oluwaseunfadugba** [comment]
Ni hao,
I can run them on my system as well. Thank you so much.
Best regards,Oluwaseun 

    On Wednesday, April 12, 2017 11:45 AM, YixinZhang92 <notifications@github.com> wrote:
 

 Sure, I have done that.—

**Comment by YixinZhang92** [comment]
Hey, Eric. Small suggestion, can you delete all files that were not edited by you? Because it will make me confused about the changes in my part. 

I know you are worried about merging, but it's ok, git can merge them in a smart way, even if your repo doesn't contain other files. 

You will get those files automatically after you merging yours.

**Comment by jamboee** [comment]
@YixinZhang92 let me do it. By the way, the parameter.in file is missing the density in the paramaters.
Only 4 files. displ_calc.cpp/.h and write2file.cpp/.h. The other .cpp i modified, mostly it was by changing the corresponding header file names. Sorry if it is causing a confusion.

**Comment by YixinZhang92** [comment]
Oh, sorry. I thought we only need velocities. I will add the density right now.

Yeah, I saw the changes from the pull request. Thank you!

By the way, what density should we use? Is 2.7 reasonable enough?

**Comment by oluwaseunfadugba** [comment]
Oh yeah, 2.7 is okay.Cheers! 

    On Wednesday, April 12, 2017 2:23 PM, YixinZhang92 <notifications@github.com> wrote:
 

 Oh, sorry. I thought we only need velocities. I will add the density right now.Yeah, I saw the changes from the pull request. Thank you!By the way, what density should we use? Is 2.7 reasonable enough?—

**Comment by jamboee** [comment]
2.7 is good. @YixinZhang92

**Comment by jamboee** [comment]
SInce all needed functions are ready, don't we need to update main.cpp to work with what we have right now? BY the way prototypes.cpp has only one function in it and i don't know if we still need. If we need it we have to create its own file too reflect what it does and then delete prototypes.cpp/.h files. if we don't need that function, we delete prototypes.cpp/.h files.  Thank you

**Comment by YixinZhang92** [comment]
Done with the read_wave.cpp by renaming it.
