### ISSUE TITLE
New things to do

### ISSUE THREAD

**Issue by YixinZhang92** [RadPattern/RadPattern2017#43]
Since we can not meet today, we just solve problems using issues.

1. Yixin is working on automatically creating names of output file names. After I created the function for outputfile_name, I will upload it as a single .cpp file. So that we can all take advantage of this function. However, in the end, where should this function go, we can discuss later.

2. Also, I have compressed the read_in functions to "process_parameter" function. Since Oluwaseun will work on the struct, I will not pull the new code "process_parameter" to the organization until the struct has been set up. 
After we had a struct, then I will fix the "process_parameter" function again to shorten a bunch of parameters to &parameter. When these all finished, I will update the read_in.cpp file to the organization.  

Let's work on what we set up to do and talk our plan using "issues" so that we can fewer conflicts when we make a pull.

Good luck to everyone, wish we will have a good weekend.

**Comment by YixinZhang92** [comment]
I am so excited to say, I have made the 'struct' work successfully. So, I basically did

Struct was created and work well. I wrote it in struct.h.
I also changed all relative parameters in main.cpp to params.xxx, so that this program can run well.
If you would like to use any values in parameters.in, just use params.xxx instead of xxx.

I changed all area_x and area_y to length_x and length_y based on Ricardo's words in class.
I have changed every area_x and area_y in my part and in main.cpp, please make sure you use the right thing in your functions.

As we talked in issue#43, I promised to make change of outputfiles.
I have done that part and gave an example in main.cpp for function mesh_gen_o (which should be deleted after you learned how to use the path).

I made change of .gitignore and Makefile to make things work. Please make sure to update yours.

**Comment by YixinZhang92** [comment]
I am so excited to say, I have made the 'struct' work successfully. So, I basically did

1.Struct was created and work well. I wrote it in struct.h.
    I also changed all relative parameters in main.cpp to params.xxx, so that this program can run well.
    If you would like to use any values in parameters.in, just use params.xxx instead of xxx.

2.I changed all area_x and area_y to length_x and length_y based on Ricardo's words in class.
    I have changed every area_x and area_y in my part and in main.cpp, please make sure you use the right thing in your functions.

3.As we talked in issue#43, I promised to make change of outputfiles.
    I have done that part and gave an example in main.cpp for function mesh_gen_o (which should be deleted after you learned how to use the path).

4.I made change of .gitignore and Makefile to make things work. Please make sure to update yours.

**Comment by oluwaseunfadugba** [comment]
Gracias Yixin!!! This is very helpful. I will include the displacement variables in the struct, loop over the mesh using a for loop instead of mesh_gen.cpp and finish up the displacement and write functions.
Cheers all,Oluwaseun 

    On Tuesday, April 18, 2017 5:46 PM, YixinZhang92 <notifications@github.com> wrote:
 

 I am so excited to say, I have made the 'struct' work successfully. So, I basically did1.Struct was created and work well. I wrote it in struct.h.
I also changed all relative parameters in main.cpp to params.xxx, so that this program can run well.
If you would like to use any values in parameters.in, just use params.xxx instead of xxx.2.I changed all area_x and area_y to length_x and length_y based on Ricardo's words in class.
I have changed every area_x and area_y in my part and in main.cpp, please make sure you use the right thing in your functions.3.As we talked in issue#43, I promised to make change of outputfiles.
I have done that part and gave an example in main.cpp for function mesh_gen_o (which should be deleted after you learned how to use the path).4.I made change of .gitignore and Makefile to make things work. Please make sure to update yours.—

**Comment by oluwaseunfadugba** [comment]
I think we can close this issue now. All done!
