### ISSUE TITLE
values of h is the same at all points

### ISSUE THREAD

**Issue by oluwaseunfadugba** [RadPattern/RadPattern2017#49]

**Comment by jamboee** [comment]
Let me work on it.

**Comment by jamboee** [comment]
h doesn't have same values everywhere. it starts at 0.78 and then drops to many different small numbers. One number is staying the same for like 10 or 20, i think this may be due to how small these numbers are and same number of significant figures. you can see it better if you make time_step very small.

Attention: beware of the memory corruption. my computer just displayed mememory map instead of the numbers. I guess cout h[i] produces more numbers than what my computer can handle. ANOTHER GOOD REASON TO DO MPI.

**Comment by jamboee** [comment]
by the way the output of h[i] is weird when time_step is less than 1. I can't figure this out
