### ISSUE TITLE
Name of prototypes.cpp 

### ISSUE THREAD

**Issue by YixinZhang92** [RadPattern/RadPattern2017#6]
The name of the file prototypes.cpp should be changed to reflect its context. It also seems obvious it has functions of different nature. It may be advisable to split into a couple of files, each with distinctive collective functions.

**Comment by ricardotaborda** [comment]
Easy change to do. Not something that should be hanging in here for 6 days.

**Comment by YixinZhang92** [comment]
I think Seun had all function names changed already. 

 @oluwaseunfadugba Seun, please check this issue and close it.

**Comment by jamboee** [comment]
This issue was not addressed. That's why I split the file Prototypes.cpp and prototypes.h in different .cpp and corresponding .h files. If you look at each created file, you will see that its name reflects what the functions in it do. As Ricardo mentioned, the functions in prototypes.cpp were of different nature. I felt like the right way to address this issue was to do what I did in my repository.

**Comment by YixinZhang92** [comment]
Oh, sorry, I see. I thought this was the issue for shortening function names. 

How about we do it separately? Like, we upload new files for our own functions and delete the original one together and later. 

Maybe it will take a whole week to make this change, we can meet sometime on Monday to talk about the detail?

**Comment by jamboee** [comment]
Yeah we will meet to make a decision and maybe details on how we organize the project. we keep uploading finished functions.

**Comment by YixinZhang92** [comment]
Agree, thanks a lot Eric!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oluwaseunfadugba** [comment]
Ni hao amigo(a),

Thank you so much for the great job! I really appreciate you all. I will work on the project tomorrow by God's grace. I am currently thinking on how to compact the functions to fix the problem of having a function for each force type and corresponding wave types. I am also thinking about fixing the time shift of the gaussian function required in the displacement calculations.

@Yixin, do you mind writing a function the just takes in a parameters.in file instead of putting the codes in the main.cpp. This will make our main.cpp file readable and easy for anybody to debug. Also, it is a little bit not clear what the EQinfo1.txt contains at the first glance on the project files, is it possible to change the file name to parameters.in or parameters.txt?

@Eric, could you please push what you have to the organisation repository of course minding that Yixin made some changes recently.
 
Thank you so much guys.

Best regards,
Oluwaseun

**Comment by jamboee** [comment]
@oluwaseunfadugba I'm updating my local repository with the changes that Yixin made. I have to make sure everything is compiling smoothly before I even update my remote repository. When I see that everything is working well, I will push changes to my remote repository. Then if we decide to use this organization, i will push to the organization repository.

**Comment by oluwaseunfadugba** [comment]
@Eric, great! Thank you so much.

**Comment by eric** [comment]
Wrong eric

**Comment by oluwaseunfadugba** [comment]
@Eric, oh sorry about that!

**Comment by jamboee** [comment]
sorry @Eric, we used the wrong username. Disregard the comments. Thank you

**Comment by oluwaseunfadugba** [comment]
@jamboee, good job!

**Comment by YixinZhang92** [comment]
1. About the input file name, you can rename it to anything you like and just run ./myprogram parameters.in(as you choose), it will run. Name of the file is not a big problem.

2. About the read in function, I will rewrite a function as simple as read_in_parameters(...) to shrink the package of read_in process.

Except for these two points, do you have any other questions about the read_in process?

**Comment by jamboee** [comment]
I think @YixinZhang92 you did a great job.

**Comment by YixinZhang92** [comment]
Thanks Eric! @jamboee

**Comment by oluwaseunfadugba** [comment]
@Yixin, thank you so much for the response. And the read_in_parameters(...)  is a great idea.
Thank you so much for the great job done. Cheers sis!
Oluwaseun

    On Saturday, April 8, 2017 9:12 PM, jamboee <notifications@github.com> wrote:
 

 I think @YixinZhang92 you did a great job.—

**Comment by YixinZhang92** [comment]
Thanks, Seun. Than you, guys! Have a good night~

**Comment by ricardotaborda** [comment]
It seems this is obsolete as the file is no longer part of the project. close the ticket.
